### PR TITLE
[release-react] Change default jsbundle file name for android

### PR DESCRIPTION
**Pull request by geof90**
To "index.android.bundle", to match RN's default https://github.com/facebook/react-native/blob/master/local-cli/generator-android/templates/src/app/react.gradle#L5

### CODE REVIEW

**Comment by lostintangent** [comment]
Do you think we should go ahead and add a new flag to the `release-react` command that allows specifying the bundle name? That way, this fix ensures the E2E works for the default file names, but if someone changes the name, they can configure it in their Obj-C/Java code, and customize it when releasing.

**Comment by geof90** [comment]
Is `--bundleName` ok?

**Comment by lostintangent** [comment]
Yep, and maybe allow "-b" as an alias?

**Comment by geof90** [comment]
@lostintangent done

**Comment by lostintangent** [comment]
Could you also update the CLI readme?

**Comment by geof90** [comment]
Yep done!

**Comment by lostintangent** [comment]
LGTM!

**Pull request merged**
