### PR TITLE
Add `build` option to `release-cordova` command

### PR DESCRIPTION
**Pull request by dtivel**
Fixes https://github.com/Microsoft/cordova-plugin-code-push/issues/92.

### CODE REVIEW

**Comment by lostintangent** [comment]
I'm not sure if we want to always run `cordova build`, since it would presumably be quite a bit slower than the `prepare` since it has to actually compile the native binary. It's definitely much simpler this way than to add a new flag to switch from using `prepare` to `build` (e.g. `code-push release-cordova MyApp ios --build`), but I'm still on the fence about which solution to this I prefer.

**Comment by scottbommarito** [comment]
I'd rather have a flag. I don't know how many people use Ionic compared to how many people use plain cordova, but slowing down everybody just for a couple people to be able to use the command is not ideal.

**Comment by candidodmv** [comment]
I accept that was said by @lostintangent, this change will affect everyone, but we need to consider that the most part of people are using the approach "prepare"

**Comment by lostintangent** [comment]
LGTM!

**Pull request merged**
