### PR TITLE
Bump superagent 6.1.0 to 8.0.0

### PR DESCRIPTION
**Pull request by seungminio**
CleanShot 2022-09-25 at 23 51 16@2x

`superagent` version warning occurs during `reaction-native-code-push` configuration.

### CODE REVIEW

**Comment by seungminio** [comment]
@microsoft-github-policy-service agree

**Comment by thewulf7** [comment]
@seungminio can you rebase your PR please?

**Comment by seungminio** [comment]
@thewulf7 I solved the conflict issue. Let me know if you need anything else! Thank you.

**Review by DmitriyKirakosyan — APPROVED** [review]

**Comment by DmitriyKirakosyan** [comment]
Closing in favor of https://github.com/microsoft/code-push/pull/808.
Updated package-lock.json file.

@seungminio Thank you so much for the contribution!

**Pull request closed without merging**
