### PR TITLE
Fix link in README.

### PR DESCRIPTION
**Pull request by fomahaut**
fin wrong url for Cordova and React-Native plugin in README.md.

### CODE REVIEW

**Comment by geof90** [comment]
LGTM!

**Comment by lostintangent** [comment]
Doh! Those typos were my bad :( thanks for the fix!

**Comment by fomahaut** [comment]
Ouch! Seams I put wrong url for Cordova plugin in this PR... and you guys fix that in minutes! :beers:

**Comment by lostintangent** [comment]
No worries :) I just quickly fixed it against master

**Pull request merged**
