### PR TITLE
Change the SDK's addAccessKey() method to be more consumable

### PR DESCRIPTION
**Pull request by silhouettes**
Infer the hostname internally within the method, and make the description field compulsory (in TypeScript at least).

### CODE REVIEW

**Comment by lostintangent** [comment]
LGTM!

**Comment by geof90** [comment]
Actually i think it would make more sense for the hostname to be customizable (and possibly renamed to something like "createdFrom"). We default it to the host name for the CLI, but there may be cases we want to explicitly annotate it with something else e.g. created from HockeyApp servers. What do you think?

**Comment by geof90** [comment]
Also if we wanted the description to be mandatory, we could throw an exception if it is not provided.

But in terms of doing what it's intended to do, this change LGTM.

**Comment by lostintangent** [comment]
I don't think the concept of a machine name makes sense with an explicitly created access key. The description is meant to encode the purpose of the key. The machine name IMO is only valuable for login-generated keys, since they indicate where the session was started, and help indicate if you want to remove it remotely. The current way that we visualize access keys in the CLI is non-ideal, and I would prefer that we add a `Type` column that is either `Login` or `Custom` (or whatever), and the `Description` column would display the machine name for login keys and the description for custom keys.

**Comment by lostintangent** [comment]
When you create an access token or SSH key on GitHub, you specify a description, and they don't capture the machine name it was created from.

**Comment by silhouettes** [comment]
Yeah, I think of the machine name more like an internal or 'generated' field that users don't specify directly, similarly to the `createdTime` field. The only reason it's on the client as opposed to the server (unlike `createdTime`) is that the server can't infer your machine name otherwise. If the user wants to annotate specific information, they can always use the `description` field. Let me know if you disagree!

**Pull request merged**
