### PR TITLE
CodePush support for NativeScript apps

### PR DESCRIPTION
**Pull request by EddyVerbruggen**
Dear friends ❤️ at Microsoft,

I'd like to kindly ask you to consider reviewing and merging this PR that adds support for NativeScript to your awesome service. This implements #247.

I've tried to align with Cordova and RN implementations as well as I could, but if you think something is not up to standard then please don't hesitate to comment on my code.

Best, and thanks for considering,
Eddy

### CODE REVIEW

**Comment by pniko** [comment]
Hi @EddyVerbruggen, we are currently discussing the best option for this PR as there are some concerns regarding how much of the native API NativeScript exposes and the risk of app store removals or rejections when used in conjunction with CodePush. Will let you know once we have decided on the best route to go later on this month. That being said, thanks for the great contribution!

**Comment by pitAlex** [comment]
Is there any news on this yet?

**Comment by patrickpereira** [comment]
+1

**Comment by philpalmieri** [comment]
Please update....

**Comment by Nikoms** [comment]
+1 :)

**Comment by iageoghe** [comment]
﻿Thanks for submitting this pull request to add NativeScript to the CodePush CLI. For the next six months, we are focused on integrating CodePush into Mobile Center and making sure that we provide the best possible experience for the existing supported platforms. Consequently, while we are very interested in NativeScript and impressed by the enthusiasm it has engendered amongst its adopters, we must close this PR in the hopes that it will be resubmitted when we can give it the attention it deserves.

**Comment by philpalmieri** [comment]
wow.. @iageoghe that is extremely disappointing...

**Comment by demetrio812** [comment]
disappointing, I was finally going to actually try and use a Microsoft product because of CodePush but that's it, good I didn't start yet

**Comment by datanotion** [comment]
Its your product/choice, but this is very disappointing indeed - so much for the spirit of contributing to open source.  Wasn't it said in #247 that "We'd definitely be interested in providing this if the interest is there"?  So then why after @EddyVerbruggen and others spends time to implement it we hear "impressed by the enthusiasm it has engendered amongst its adopters we must close this PR".

Those statements conflict.

Sounds like the market is ripe for an alternative solution to CodePush.

**Comment by philpalmieri** [comment]
Not to mention, it USED TO WORK - so the architecture is there...  I can't see a non-political/business reason not to continue to support nativescript...

**Comment by pitAlex** [comment]
Its nativescript and its power of tapping into the native api. You know that you can access private api with it on iOS? I did a few experiments. That is what caused all the concerns. You could push an update that access those apis and that is not allowed by apple. With this risk in mind you just don't know if apple will allow it or not when they realize this, so your app can end up being rejected just because it has the ability to update. I'm disappointed too but I can understand the concerns and the choice not to support it.

**Comment by EddyVerbruggen** [comment]
@pitAlex That's entirely true, but that's also true for the initial not-codepushed AppStore version. You can easily circumvent Apple's static code analysis - heck, even with a fully native app, or Cordova, or RN.

I'm as disappointed as you are, obviously, but the reason my PR was rejected is because what @iageoghe explained, not because MSFT deems NativeScript a dangerous or inferior technology (on the contrary is what I heard). But - shortly after they encouraged us to create this PR MSFT management decided to focus their scarce resources on the CodePush platforms they already support and integrate those into their new Mobile Center solution.

I would love to support NativeScript within Mobile Center but AFAIK it's closed source so they'd have to do it themselves and just don't have the resources to take an additional platform on board. However, MSFT promised to reevaluate the situation over time and consider any other platforms (in addition to iOS, Android, Xamarin, Cordova and RN) like NativeScript to be added to Mobile Center if there is sufficient demand (and resources in their team).

I respect their decision, I hope you do to, and let's all hope it won't take too long for NativeScript to become part of Mobile Center as well.

In the meanwhile we should look for other CodePush-like solutions given that for this PR to work I've already created a clientside plugin that does the legwork, we "only" need a cloud service that stores and serves the code updates.. but let's take that discussion to the [NativeScript forum](https://discourse.nativescript.org/).

**Comment by sm1ddy** [comment]
Fair enough but this is still disappointing.

I'll be avoiding Microsoft solutions.

**Comment by shiv19** [comment]
very disappointing :(

**Comment by csbok** [comment]
disappointing

**Comment by uzarsalan** [comment]
Very disappointed

**Comment by Sharique-Hasan** [comment]
Still disappointing

**Comment by alvirtuoso** [comment]
+

**Comment by jdnichollsc** [comment]
wowww... so Microsoft doesn't have the resources (unbelievable) or Microsoft prefer React Native (Some alliance with Facebook or because Microsoft developers prefer React Native)?
6 months? It's been 8 months since the contribution, I'm surprised that kind of answers ...

**Comment by pniko** [comment]
@kayveedw @jdnichollsc In full transparency, we don't feel our React Native and Cordova implementations for CodePush represent the best versions of themselves. We just released the Cordova preview SDK for App Center and are in the process of rewriting the CodePush SDK's to enable better rollback support along with a whole slew of features that have been requested by our current users for some time now. After we finish things up around March we'll revisit this again when we aren't spread so thin.

**Comment by jdnichollsc** [comment]
@pniko thanks Patrick for the clarification! If the community can help you guys, let us know 👍 Also, @EddyVerbruggen thanks for all your help, you are the best! 🥇

**Comment by ndcunningham** [comment]
Any updates on this it's passed March 😃 ?

**Comment by Zakeelm** [comment]
Hey! 

We recognize the value of NativeScript support and this is something that is still definitely on our radar. While we still don't have an ETA on this at the moment due to the reprioritization of our team's backlog, we haven't forgotten about this item. Hopefully, we can revisit this conversation sometime soon. 😊

**Comment by jdnichollsc** [comment]
Any date expected to do that implementation? :)

**Comment by jdnichollsc** [comment]
Any job opportunity on Microsoft to implement that feature? 😅

**Comment by bryanrideshark** [comment]
Hi @Zakeelm , @iageoghe , Microsoft team.

Not to be pesky, but can you re-evaluate doing this project for Q1 2019? My company currently uses Code Push for our Angular Cordova app. We are sort of stuck with Cordova - we can't afford to have a dedicated mobile team, and because we chose Angular, React Native really isn't an option. The only logical choice remaining to us is NativeScript, but without the ability to release quick updates via Code Push, that looks much less viable.

If we were able to use Code Push (even a rough, beta, not that great and buggy version), we could likely migrate our codebase to NativeScript. This would represent a huge value add for our company.

Would you consider re-evaluating a NativeScript implementation for Q1 2019?

**Comment by RoyiNamir** [comment]
You see ..... That's one of the problems about NS. it doesn't have a good PR (public relation). ( as opposed to other FW).

Started with the poor decision about discourage site  , making Stackoverflow to almost not to have any mass of info about NS) - thankfully they're closing it now (read only) .


Maybe this thread is not the right place to give it a priority. 
We might be need to think of something else using media.
Nobody -sees this thread. But everybody sees twitter. especially `@microsoft`.
(IMO)

**Comment by digitalhurricane-io** [comment]
Come on guys...

**Comment by pniko** [comment]
We're 100% listening. 🙏 There are many platforms we'd like to add to CodePush and App Center in general, but we're already stretched a bit thin on support. Rather than enabling just NativeScript we're looking at a more generic option based on target OS rather than the tooling on top so those that want to play around with different options and implementations have the freedom to.

**Comment by jdnichollsc** [comment]
Interesting, it seems a little complicated but I want to see that 😊

**Comment by Sharpie360** [comment]
Any updated on this in 2019? Elaboration on "over-the-air" updates?

**Comment by jdnichollsc** [comment]
Yes, we need this, I prefer NativeScript instead of React Native (working hard in this last year with React Native for this reason) :/

**Comment by EddyVerbruggen** [comment]
For folks interested, there's a new proposal for adding NativeScript support to App Center here: https://github.com/Microsoft/appcenter-cli/issues/542

@patniko Would love to learn more about the generic option you mentioned, but for the time being, teaming up with App Center seems like the best option.

**Comment by shirakaba** [comment]
@patniko 

> Hi @EddyVerbruggen, we are currently discussing the best option for this PR as there are some concerns regarding how much of the native API NativeScript exposes and the risk of app store removals or rejections when used in conjunction with CodePush.

Although this comment is two years old, I felt I should respond to the security concerns. Apple recently accepted my NativeScript REPL app (which allows you to call all the NativeScript APIs at run-time) into the App Store: https://github.com/shirakaba/nside . Apparently they're not concerned about the security implications; they're confident in their App Sandbox.

**Pull request closed without merging**
